<?php
$daftarProdi = [
                // Fakultas Ilmu Pendidikan
                'Pendidikan Luar Sekolah (S1)',
                'Teknologi Pendidikan (S1)',
                'Pendidikan Guru PAUD (S1)',
                'Pendidikan Guru Sekolah Dasar (S1)',
                'Psikologi (S1)',
                'Bimbingan dan Konseling (S1)',
                // Fakultas Bahasa & Seni
                'Pendidikan Bahasa Mandarin (S1)',
                'Pendidikan Bahasa Inggris (S1)',
                'Sastra Inggris (S1)',
                'Pendidikan Seni Musik (S1)',
                'Pendidikan Seni Tari (S1)',
                'Desain Komunikasi Visual (D3)',
                'Seni Rupa (S1)',
                'Pendidikan Seni Rupa (S1)',
                'Pendidikan Bahasa Jepang (S1)',
                'Sastra Prancis (S1)',
                'Pendidikan Bahasa Arab (S1)',
                'Pendidikan Bahasa Prancis (S1)',
                'Sastra Jawa (S1)',
                'Pendidikan Bahasa Jawa (S1)',
                'Sastra Indonesia (S1)',
                'Pendidikan Bahasa dan Sastra Indonesia (S1)',
                // Fakultas Ilmu Sosial
                'Pendidikan IPS (S1)',
                'Ilmu Politik (S1)',
                'Pendidikan Sosiologi & Antropologi (S1)',
                'Pendidikan PKn (S1)',
                'Survey dan Pemetaan Wilayah (D3)',
                'Geografi (S1)',
                'Pendidikan Geografi (S1)',
                'Ilmu Sejarah (S1)',
                'Pendidikan Sejarah (S1)',
                // Fakultas Matematika dan IPA
                'Ilmu Lingkungan (S1)',
                'Sistem Informasi (S1)',
                'Farmasi (S1)',
                'Teknik Informatika (S1)',
                'Pendidikan IPA (S1)',
                'Biologi (S1)',
                'Pendidikan Biologi (S1)',
                'Kimia (S1)',
                'Pendidikan Kimia (S1)',
                'Fisika (S1)',
                'Pendidikan Fisika (S1)',
                'Statistika Terapan dan Komputasi (D3)',
                'Matematika (S1)',
                'Pendidikan Matematika (S1)',
                // Fakultas Teknik
                'Pendidikan Kesejahteraan Keluarga (S1)',
                'Pendidikan Tata Boga (S1)',
                'Pendidikan Teknik Otomotif (S1)',
                'Teknik Kimia (S1)',
                'Pendidikan Tata Kecantikan (S1)',
                'Pendidikan Tata Busana (S1)',
                'Teknik Elektro (S1)',
                'Pendidikan Teknik Informatika dan Komputer (S1)',
                'Pendidikan Teknik Elektro (S1)',
                'Teknik Mesin (S1)',
                'Pendidikan Teknik Mesin (S1)',
                'Teknik Sipil (S1)',
                'Teknik Arsitektur (S1)',
                'Pendidikan Teknik Bangunan (S1)',
                // Fakultas Ilmu Keolahragaan
                'Gizi (S1)',
                'Pendidikan Jasmani Sekolah Dasar (S1)',
                'Kesehatan Masyarakat (S1)',
                'Pendidikan Kepelatihan Olah Raga (S1)',
                'Ilmu Keolahragaan (S1)',
                'Pendidikan Jasmani, Kesehatan dan Rekreasi (S1)',
                // Fakultas Ekonomi
                'Ekonomi Pembangunan (S1)',
                'Manajemen Perkantoran (D3)',
                'Manajemen (S1)',
                'Akuntansi (D3)',
                'Akuntansi (S1)',
                'Pendidikan Ekonomi Administrasi Perkantoran (S1)',
                'Pendidikan Ekonomi Koperasi (S1)',
                'Pendidikan Ekonomi Akuntansi (S1)',
                // Fakultas Hukum
                'Ilmu Hukum (S1)',
                // Pascasarjana
                'Pendidikan Geografi (S2)',
                'Pendidikan Bahasa (S3)',
                'Pendidikan Olahraga (S3)',
                'Manajemen Kependidikan (S3)',
                'Penelitian dan Evaluasi Pendidikan (S2)',
                'Kurikulum dan Teknologi Pembelajaran (S2)',
                'Pendidikan Seni (S2)',
                'Pendidikan Dasar (S2)',
                'Pendidikan Olahraga (S2)',
                'Pendidikan Matematika (S2)',
                'Pendidikan IPA (S2)',
                'Pendidikan IPS (S2)',
                'Pendidikan Bahasa Inggris (S2)',
                'Pendidikan Bahasa Indonesia (S2)',
                'Bimbingan dan Konseling (S2)',
                'Manajemen Pendidikan (S2)'];
?>
